apiVersion: apps.nebula-graph.io/v1alpha1
kind: NebulaCluster
metadata:
  name: nebula
spec:
  graphd:
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
    replicas: 1
    image: vesoft/nebula-graphd
    #version: v3.1.3
    service:
      type: NodePort
      externalTrafficPolicy: Local
    logVolumeClaim:
      resources:
        requests:
          storage: 2Gi
      storageClassName: "csi-wekafs-fs"
  metad:
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
    replicas: 1
    image: vesoft/nebula-metad
    #version: v3.1.3
    dataVolumeClaim:
      resources:
        requests:
          storage: 2Gi
      storageClassName: "csi-wekafs-fs"
    logVolumeClaim:
      resources:
        requests:
          storage: 2Gi
      storageClassName: "csi-wekafs-fs"
  storaged:
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
    replicas: 3
    image: vesoft/nebula-storaged
    #version: v3.1.3
    dataVolumeClaim:
      resources:
        requests:
          storage: 2Gi
      storageClassName: "csi-wekafs-fs"
    logVolumeClaim:
      resources:
        requests:
          storage: 2Gi
      storageClassName: "csi-wekafs-fs"
  reference:
    name: statefulsets.apps
    version: v1
  schedulerName: default-scheduler
  imagePullPolicy: Always
